### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by Beldaa**
## Issue
None
## Details
Just replaced the word 'intialize' with 'initialize' in some comments & logs

### CODE REVIEW

**Comment by WoodNeck** [comment]
Hello @Beldaa! Thanks for the contribution
This PR looks completely good to me :)

**Review by mixed — APPROVED** [review]
Thank you for your PR :)

**Review by daybrush — APPROVED** [review]
Thank you for PR :)

**Comment by WoodNeck** [comment]
@Beldaa Can you modify the commit message a bit?
Looks like we forgot to add one in this repo, but we use the [Angular commit guidelines](https://github.com/naver/egjs-flicking/blob/master/CONTRIBUTING.md).

Just a `docs: fix typo` would be fine for us

**Comment by Beldaa** [comment]
@WoodNeck it's ok now?

**Comment by WoodNeck** [comment]
@Beldaa I mean git commit message. Can you modify then force-push it?

```sh
git commit --am
# Then
git push -f
```

**Comment by Beldaa** [comment]
I'll re-open it clean

**Comment by WoodNeck** [comment]
@Beldaa Okay 😄, sorry for the missing guidelines!

**Pull request closed without merging**
