### PR TITLE
Stereo safari bug

### PR DESCRIPTION
**Pull request by huwllewellyn**
View the safari test page by going to 
http://0.0.0.0:8080/demo/examples/panoviewer/projection-type/equirect_video_stereoscopic.html

BUG: one canvas does not render in Safari
Screen Shot 2019-05-06 at 12 47 10 pm

### CODE REVIEW

**Comment by jongmoon** [comment]
@huwllewellyn Thank you for PR. I'll check it soon!

**Comment by jongmoon** [comment]
@huwllewellyn By your example, I found that Safari can render only one canvas as you mentioned. 

image

But it's difficult to find difference what you've made to fix it because distributed files are too big to compare. so github does not show difference. 
image

and my computer are crying while comparing.

Could you show me what is the core code to fix this problem?

**Comment by huwllewellyn** [comment]
I wasn't able to find a fix, sorry.

**Comment by jongmoon** [comment]
@huwllewellyn Ah ha~ you want to report issue by this pr. I got it!

**Comment by huwllewellyn** [comment]
@jongmoon I wish I could be more helpful to help you solve the problem.

**Pull request closed without merging**
