### PR TITLE
docs: fix videojs demo not working on iOS

### LINKED ISSUE #378: Not working on iOS
## Description
The latest code is not working on iOS. Tested on the following devices:

* iPhone 8 - iOS 15.2
* iPhone Xs Max - iOS 15.2

## Steps to check or reproduce

1. Open the site https://naver.github.io/egjs-view360/examples/panoviewer/etc/videojs.html on an iPhone running the latest version of iOS (v15)
2. Accept the motion and control request
3. The video player is stuck with the 360 icon and the video does not start

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#378

## Details
This fixes #378

### CODE REVIEW

**Comment by juancarlosjr97** [comment]
Great job @WoodNeck , I just tested the branch on my iPhone and other devices that were presented the issue and it is working :)

**Comment by WoodNeck** [comment]
@juancarlosjr97 
Great to hear that :) Thanks for testing!

**Review by mixed — APPROVED** [review]
LGTM

**Review by daybrush — APPROVED** [review]
LGTM

**Review by malangfox — APPROVED** [review]
LGTM

**Comment by juancarlosjr97** [comment]
jonah-hill-yay

Awesome :)

**Pull request merged**
