### PR TITLE
feat(CubeStripRenderer): add new cubestrip renderer for performance & support EAC

### PR DESCRIPTION
**Pull request by jongmoon**
## Issue

#190 : I changed renderer as eg.Component based. So it can triggers errors to outside of component and also make coverage high. (https://github.com/naver/egjs-view360/pull/221/commits/5b7237ac43ee06db2179160507f1c4b2023c98ff)

#218 
#220 

## Details
  - Add new renderer type : "cubestrip"
  - It makes available to show EAC (Equi Angular Cubemap) Format which is used on Youtube.

### CODE REVIEW

**Comment by jongmoon** [comment]
@younkue I'll add unit test code for this.

**Comment by jongmoon** [comment]
## Manual Test List (TODO)

### order test (with yawpitch rotation)
  - RLUDFB: Facebook, Three.js (default)
   - Check if it is working as default
  - RLUDBF: NAVER
   - need set tileConfig property of cubemapConfig as follows.
    - `[{flipHorizontal: true, rotation: 0}, {flipHorizontal: true, rotation: 0}, {flipHorizontal: true, rotation: 180}, {flipHorizontal: true, rotation: 0}, {flipHorizontal: true, rotation: 0}, {flipHorizontal: true, rotation: 0}]`
  - BLFDRU: Youtube order
    - `[{rotation: 0}, {rotation: 0}, {rotation: 0}, {rotation: 90}, {rotation: -90}, {rotation: 90}]`

### EAC Test
  - is Working properly when image ratio is not 3:2.


## Environtment
  - Adopt async/await
     - [egjs/infiniteGrid](https://github.com/naver/egjs-infinitegrid/blob/ac0c5487281a0490f13600e81c30d9b6d05e99d1/packages/react-infinitegrid/test/InfiniteGrid.test.js) has adopted

**Comment by jongmoon** [comment]
NAVER format should be 1x6 tile config. But 1x6 is not supported on `ProjectionType.CubeStrip` Mode yet. 1x6 is supported  on `ProjectionType.CUBEMAP` Mode.

**Comment by younkue** [comment]
LGTM

**Pull request merged**
