### PR TITLE
fix: video is not playable because of keepUpdate value

### LINKED ISSUE #349: Video is not playable after v3.4.2 update
## Description
Video is not playable after v3.4.2 update
This is due to a tiny script mistake in setting a `keepUpdate` value in `setImage` method.

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#349 

## Details
This fixes #349

### CODE REVIEW

**Review by mixed — APPROVED** [review]
Is there no need to write test code?

**Review by daybrush — APPROVED** [review]
LGTM

**Comment by WoodNeck** [comment]
> Is there no need to write test code?

I thought this fix was too trivial so I've missed that, but I rethought that it'll need one so I've added it.

**Review by mixed — APPROVED** [review]
🤛

**Pull request merged**
